RED-397 Added hyperlink to landing logo
rederly/frontend pull request #406
Opened 2021-01-28 17:50 UTC by red-tt-bear

2021-01-30 00:16 UTC, doombot-exe approved these changes

2021-01-30 00:28 UTC, PanopticaRising approved these changes

2021-01-30 00:29 UTC, PanopticaRising requested changes

2021-01-30 00:29 UTC, PanopticaRising commented on src/Components/LandingPageWrapper.tsx
> +                <a href="/" style={{alignSelf: 'center'}}>
This should be a Link tag.

2021-02-01 14:56 UTC, doombot-exe approved these changes

2021-02-01 16:03 UTC, PanopticaRising approved these changes

2021-02-01 16:04 UTC, merged